# all:
# 	@echo "SketchyBar: Compiling event monitors..."
# 	@(cd event_providers && $(MAKE)) >/dev/null && echo "✓ Event monitors ready"
# 	@echo "SketchyBar: Compiling menu helpers..."
# 	@(cd menus && $(MAKE)) >/dev/null && echo "✓ Menu helpers ready"

all:
	@(cd event_providers && $(MAKE))
	@(cd menus && $(MAKE))
