[metadata]
name = "ssh-switcher"
description = "SSH host switcher with tmux window rename"
requirements = ["grep", "tr", "cut", "awk"]

[source]
command = "grep -E '^Host(name)? ' $HOME/.ssh/config | tr -s ' ' | cut -d' ' -f2- | tr ' ' '\n' | grep -v '^$'"

[preview]
command = "awk '/^Host / { found=0 } /^Host (.*[[:space:]])?'{}'([[:space:]])?$/ { found=1 } found' $HOME/.ssh/config | bat -n --color=always -l ssh_config -p"
# command = "awk '/^Host / { found=0 } /^Host (.*[[:space:]])?'{}'([[:space:]].*)?$/ { found=1 } found' $HOME/.ssh/config"

[keybindings]
enter = "actions:connect"

[actions.connect]
description = "SSH into the selected host"
command = "tmux rename-window '{}' && ssh '{}'"
mode = "execute"
