#!/bin/sh

# Aliases
alias gopen="open \$(git config --get remote.origin.url)" # Open the github directory on the browser
alias todo="vim ~/Github/University/TODO.md"
alias safari="open /Applications/Safari.app"
alias showD="defaults write com.apple.finder CreateDesktop -bool true;killall Finder" # show the Dock
alias hideD="defaults write com.apple.finder CreateDesktop -bool false;killall Finder" # hide the Dock
alias noDSS="defaults write com.apple.desktopservices DSDontWriteNetworkStores true"
alias locate_update="sudo /usr/libexec/locate.updatedb" # Update locate database
alias pip3-update="pip3 list --outdated | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U"
alias weather="curl http://wttr.in/trieste"
alias DSSdelete="find . -name '.DS_Store' -type f -delete"
alias icat="kitty +kitten icat"
alias cat_all="for f in *; do [ -f "$f" ] && echo "Filename: $f" && cat "$f" && echo; done" # Cat all files in a directory with respective filename

# Better commands
alias v="nvim"
alias vi="nvim"
alias df="duf"
alias ps="procs"
alias ping="gping"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias grep="grep --color"
alias ls="lsd"

# alias find="fd"
alias l="lsd -la"
alias top='btop'
alias mpv='mpv --geometry=50%'
alias history='history 1'
alias mtype='tt --notheme -showwpm'
alias intel='arch -arch x86_64'
alias jl='jupyter lab'
# alias cat='bat'
alias oo='cd ~/Documents/second_brain'
alias ltree='lsd --tree'
alias openvpn="/opt/homebrew/opt/openvpn/sbin/openvpn"
alias tmate='tmate -f ~/.config/tmate/tmate.conf'

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
alias wget="wget --hsts-file ~/.cache/wget/wget-hsts"

# git aliases
alias g='git'
alias gs='git status'
alias gaa='git add --all'
alias gb='git branch'
alias gst='git status'
alias gcam='git commit -a -m'
alias gco='git checkout'
alias gd='git diff'
alias gp='git push'
alias gr='git remote'

# web searches
alias rogan="open https://open.spotify.com/show/4rOoJ6Egrf8K2IrywzwOMk"
alias lex="open https://open.spotify.com/show/2MAi0BvDc6GTFvKFPXnkCL"
alias chat="open https://web.whatsapp.com/" # Open whatsapp
alias youtube="open https://www.youtube.com/"
alias github="open https://github.com/"


# Set custom commands
# Set up fast movement with fuzzy finding
show_file_or_dir_preview="if [ -d {} ]; then lsd --tree {} --color=always --icon=always | head -200; else bat -n --color=always --line-range :500 {}; fi"

# Set Up zoxide Functions 
f() {
    cd "$(zoxide query --list | fzf --height 40% --reverse --border --ansi --preview $show_file_or_dir_preview)"
}


# Find applications
fa() {
  yabai -m query --windows |
    jq -r '.[] | "\(.id)\t\(.app)\t\(.title)"' |
    awk -F $'\t' '
      { printf "\033[36m%-5s\033[0m\t\033[35m%-20s\033[0m\t%s\n",
               $1, $2, $3 }
    ' |
    fzf \
      --ansi \
      --delimiter=$'\t' \
      --with-nth=2,3 \
      --height=40% \
      --reverse \
      --border \
      --prompt="Window: " \
      --header=$'\033[36mApp\033[0m               \033[0mTitle' \
      --preview-window="right,60%,border-left" \
      --preview="
        yabai -m query --windows --window {1} |
        jq -r '\"App:    \(.app)\nTitle:  \(.title)\nID:     \(.id)\nSpace:  \(.space)\nDisplay: \(.display)\nFrame:  \(.frame.x) \(.frame.y) \(.frame.w) \(.frame.h)\"' |
        bat --style=plain --color=always --language=yaml --line-range :20
      " \
      --bind 'enter:execute(yabai -m window --focus {1})+abort'
}

# Load tmux functions
if [ -f $XDG_CONFIG_HOME/scripts/tmux-utils ]; then
  source $XDG_CONFIG_HOME/scripts/tmux-utils
fi

# Aliases for quick use:
alias ta='tmux attach'       # shortcut
alias t='tmux_start'        # start/switch
alias tq='tmux_stop'        # quit session or server
alias tl='tmux_fzf_attach'  # attach via fzf to the listed sessions
alias tw='tmux_fzf_window'  # switch window via fzf
alias tk='tmux_fzf_kill'    # kill session via fzf
alias tf='tmux_sessionize'  # sessionizer
