#!/bin/sh

# Aliases
gopen() {
  local url
  url=$(git remote get-url origin 2>/dev/null || git remote get-url thlm 2>/dev/null)
  url="${url#git@github.com:}"
  url="${url#https://github.com/}"
  url="${url%.git}"
  open "https://github.com/$url"
}

# Useful browser commands
# ask Perplexity something ...
_ask() {
  if [ -z "$*" ]; then
    open "https://www.perplexity.ai/"
    return
  fi

  open "https://www.perplexity.ai/search?q=$(jq -nr --arg q "$*" '$q | @uri')"
}

alias ask='noglob _ask'

alias todo="vim ~/Github/University/TODO.md"
alias safari="open /Applications/Safari.app"
alias showD="defaults write com.apple.finder CreateDesktop -bool true;killall Finder" # show the Dock
alias hideD="defaults write com.apple.finder CreateDesktop -bool false;killall Finder" # hide the Dock
alias noDSS="defaults write com.apple.desktopservices DSDontWriteNetworkStores true"
alias locate_update="sudo /usr/libexec/locate.updatedb" # Update locate database
alias pip3-update="pip3 list --outdated | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U"
alias weather="curl http://wttr.in/trieste"
alias DSSdelete="find . -name '.DS_Store' -type f -delete"

cat_all() {
  local recursive=0
  # Check if the first argument is -r
  if [ "$1" = "-r" ]; then
    recursive=1
    shift
  fi

  if [ $recursive -eq 1 ]; then
    # Recursive: find all files in current directory and subdirectories
    find . -type f | while IFS= read -r f; do
      echo "Filename: $f"
      cat "$f"
      echo
    done
  else
    # Non-recursive: only files in current directory
    for f in *; do
      if [ -f "$f" ]; then
        echo "Filename: $f"
        cat "$f"
        echo
      fi
    done
  fi
}

shome() {
  cd "$(tmux display-message -pF '#{session_path}')"
}

# Better commands
alias v="nvim"
alias vi="nvim"
alias df="duf"
alias ps="procs"
# alias ping="gping"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias grep="grep --color"
alias ls="lsd"
alias cat='bat'

# alias find="fd"
alias l="lsd -la"
alias top='btop'
alias mpv='mpv --geometry=50%'
alias history='history 1'
alias mtype='tt --notheme -showwpm'
alias intel='arch -arch x86_64'
alias jl='jupyter lab'
alias oo='cd ~/Documents/second_brain'
alias ltree='lsd --tree'
alias openvpn="/opt/homebrew/opt/openvpn/sbin/openvpn"
alias tmate='tmate -f ~/.config/tmate/tmate.conf'

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
alias wget="wget --hsts-file ~/.cache/wget/wget-hsts"

# git aliases
alias g='git'
alias gs='git status'
alias gaa='git add --all'
alias gb='git branch'
alias gst='git status'
alias gcam='git commit -a -m'
alias gco='git checkout'
alias gd='git diff'
alias gp='git push'
alias gr='git remote'
alias lg='lazygit'

# web searches
alias youtube="open https://www.youtube.com/"
alias github="open https://github.com/"

# Set custom commands
# Set up fast movement with fuzzy finding
show_file_or_dir_preview="if [ -d {} ]; then lsd --tree {} --color=always --icon=always | head -200; else bat -n --color=always --line-range :500 {}; fi"

# Set Up zoxide Functions 
# f() {
#     cd "$(zoxide query --list | fzf --height 40% --reverse --border --ansi --preview $show_file_or_dir_preview)"
# }

alias f="tv zoxide --inline"

# 1. Start or switch to a tmux session named after the current directory
function tmux_start() {
  local session_name="${PWD##*/}"
  session_name="${session_name//./_}"

  if [ -n "$TMUX" ]; then
    if ! tmux has-session -t "$session_name" 2>/dev/null; then
      TMUX='' tmux new-session -Ad -s "$session_name" -c "$PWD"
    fi
    tmux switch-client -t "$session_name"
  else
    tmux new-session -As "$session_name" -c "$PWD"
  fi
}

# 2. Stop (kill) the current tmux session or the server if not inside tmux
function tmux_stop() {
  if [ -n "$TMUX" ]; then
    tmux kill-session -t "$(tmux display-message -p '#S')"
  else
    echo "Not in a tmux session. Killing tmux server."
    tmux kill-server
  fi
}

alias t='tmux_start'        # start/switch
alias tq='tmux_stop'        # quit session or server
