-- Right items (R to L)
require("items.widgets.battery")
require("items.widgets.wifi")
require("items.widgets.volume")
require("items.widgets.control_center")
require("items.widgets.keyboard")
require("items.widgets.agents")

-- require("items.widgets.metrics")
-- require("items.widgets.media")
