"call plug#begin()
"Plug 'arcticicestudio/nord-vim'
"Plug 'jremmen/vim-ripgrep'
"Plug 'tpope/vim-fugitive'
"Plug 'leafgarland/typescript-vim'
"Plug 'vim-utils/vim-man'
"Plug 'lyuts/vim-rtags'
" Plug 'git@github.com:Valloric/YouCompleteMe.git'
"Plug 'mbbill/undotree'
"call plug#end()

"colorscheme nord

" change the location of viminfo
set viminfo+=n~/.vim/viminfo

syntax on
set tabstop=4 softtabstop=4
set smartindent

set nowrap
set incsearch


" set number how I like them 
set number relativenumber
set hlsearch
set ruler

set syntax=markdown

" posso creare azioni che vengono svolte dopo che ho salvato un file
