#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config external_bar                 all:33:0\
                mouse_follows_focus         off\
                focus_follow_mouse          off\
                window_placement            first_child\
                window_placement            second_child\
                window_shadow               float\
                window_opacity_duration     0.2\
                window_opacity              on\
                active_window_opacity       1.0\
                normal_window_opacity       0.9\
                insert_feedback_color       0xff9dd274\
                split_ratio                 0.50\
                auto_balance                on\
                mouse_modifier              alt\
                mouse_action1               move\
                mouse_action2               resize\
                mouse_drop_action           swap\
                window_animation_duration   0.0\
                window_animation_easing     ease_in_expo\
                layout                      bsp\

# yabai -m config menubar_opacity 0.0
# yabai -m config mouse_follows_focus on
#
# yabai -m config split_ratio                  0.55
# yabai -m config auto_balance                 on # Auto focus on mouse that is what I want

yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

# Rules to move open applications in a specific space
yabai -m rule --add app="Zen Browser"           space=1
yabai -m rule --add app="Ghostty"               space=2
yabai -m rule --add app="WhatsApp"              space=5

# yabai -m rule --add app="FaceTime"   space=4
# yabai -m rule --add app="Microsoft Teams"   space=4

# ===== Rules ==================================

yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="Clock" app="^Clock$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Raycast" app="^Raycast$" title="^Raycast Settings$" manage=off
# yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Mail" app="^Mail$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="Time Machine" app="^Time Machine$" title=".*" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title=".*" manage=off


# ====== Signal ===================================

# Add signal to make yabai focus the other window when I close one
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
