#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             first_child
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config window_border_blur           0
# yabai -m config active_window_border_color   0xFFD08770 # orange
yabai -m config active_window_border_color   0xFFEBCB8B # yellow
# yabai -m config active_window_border_color   0xFF81A1C1 # blue
# yabai -m config active_window_border_color   0xFFA3BE8C # Green
yabai -m config normal_window_border_color   0xFF4C566A
# yabai -m config normal_window_border_color   0xFF2E3440
yabai -m config insert_feedback_color        0xff61afef
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
# New windows take a bit more space
# yabai -m config split_ratio                  0.55

yabai -m config layout                       bsp
yabai -m config top_padding                  18
yabai -m config bottom_padding               13
yabai -m config left_padding                 13
yabai -m config right_padding                13
yabai -m config window_gap                   13

yabai -m space 1 --label 'I'
yabai -m space 2 --label 'II'
yabai -m space 3 --label 'III'
yabai -m space 4 --label 'IV'
yabai -m space 5 --label 'V'
yabai -m space 6 --label 'VI'
yabai -m space 7 --label 'VII'
yabai -m space 8 --label 'VIII'
yabai -m space 9 --label 'IX'
yabai -m space 10 --label 'X'

# ^^ these are annoying
yabai -m rule --add app="Alacritty"     space=1
yabai -m rule --add app="Safari"        space=1
yabai -m rule --add app="Discord"       space=5
yabai -m rule --add app="Spotify"       space=6

# ===== Rules ==================================

yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Mail" app="^Mail$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="FaceTime" app="FaceTime" title="FaceTime" manage=float

yabai -m config external_bar all:27:0
# yabai -m config external_bar all:0:0

echo "yabai configuration loaded.."
