#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
#

yabai -m config external_bar                 all:27:0\
                mouse_follows_focus         off\
                window_placement            first_child\
                window_placement            second_child\
                window_shadow               float\
                window_opacity              on\
                active_window_opacity       1.0\
                normal_window_opacity       0.9\
                insert_feedback_color       0xff61afef\
                split_ratio                 0.50\
                auto_balance                on\
                mouse_modifier              fn\
                mouse_action1               move\
                mouse_action2               resize\
                mouse_drop_action           swap\
                window_animation_duration   0.0\
                window_animation_easing     ease_in_expo\
                layout                      bsp\

# yabai -m config menubar_opacity              0.0 # Completely disable menu bar
# New windows take a bit more space
# yabai -m config split_ratio                  0.55
#
# yabai -m config auto_balance                 on # Auto focus on mouse that is what I want

yabai -m config top_padding                  18
yabai -m config bottom_padding               13
yabai -m config left_padding                 13
yabai -m config right_padding                13
yabai -m config window_gap                   13

yabai -m space 1 --label 'I'
yabai -m space 2 --label 'II'
yabai -m space 3 --label 'III'
yabai -m space 4 --label 'IV'
yabai -m space 5 --label 'V'
yabai -m space 6 --label 'VI'
yabai -m space 7 --label 'VII'
yabai -m space 8 --label 'VIII'
yabai -m space 9 --label 'IX'
yabai -m space 10 --label 'X'

# ^^ these are annoying
yabai -m rule --add app="Alacritty"     space=1
yabai -m rule --add app="Safari"        space=1
yabai -m rule --add app="Discord"       space=5
yabai -m rule --add app="Spotify"       space=6

# ===== Rules ==================================

yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Mail" app="^Mail$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# yabai -m rule --add label="Little Arc" app="^Arc$" title="^Space.*" manage=off
# yabai -m config external_bar all:0:0#

echo "yabai configuration loaded.."

# yabbie -m config active_window_border_color   0xFFD08770 # orange
# yabai -m config active_window_border_color   0xFFEBCB8B # yellow
# yabai -m config active_window_border_color   0xFF81A1C1 # blue
# yabai -m config active_window_border_color   0xFFA3BE8C # Green
# yabai -m config normal_window_border_color   0xFF4C566A
# yabai -m config normal_window_border_color   0xFF2E3440
#
# yabai -m config window_border_width          4
# yabai -m config window_border_radius         12

# add these lines to the bottom of your yabairc file
# they're needed to trigger a custom event in sketchybar that we will later define in sketchybarrc


# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
